# Generated by Django 3.2.3 on 2021-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=10)),
                ('news_title', models.CharField(max_length=100)),
                ('news_genre', models.CharField(max_length=100)),
                ('news_plot', models.CharField(max_length=500)),
                ('news_link', models.CharField(max_length=200)),
                ('news_rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('news_title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
