# Generated by Django 3.2.3 on 2021-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_alter_news_news_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, max_length=5000),
        ),
    ]
